import { Inter } from "next/font/google";
import "./globals.css";
import Pwa from './pwa'

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.json",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Pwa/>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
